import type {
  AdminNotification,
  BoothCustomization,
  BoothTemplate,
  BoothTemplateCustomizationConfig,
  BoothTemplateUsage,
  BoothType,
  ExhibitorCatalogProduct,
  Expo,
  ExpoBoothTemplateAssignment,
  ExpoCategory,
  GoLIVEEvent,
  HallSlotUsage,
  HallTemplate,
  HallTemplateSlot,
  HallTemplateUsage,
  LiveComment,
  ModelAsset,
  SellerBoothRegistration,
  StreamSession,
} from "@/lib/tradexpo/types"

const now = new Date()

function isoOffset(hours: number) {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString()
}

export const mockAssets: ModelAsset[] = [
  {
    id: "asset-glb-hall-1",
    fileName: "modern-hall.glb",
    fileUrl: "https://picsum.photos/seed/hall1/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-thumb-hall-1",
    fileName: "modern-hall-thumb.webp",
    fileUrl: "https://picsum.photos/seed/hall1thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-blend-hall-1",
    fileName: "modern-hall.blend",
    fileUrl: "https://example.com/files/modern-hall.blend",
    kind: "blend",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-glb-hall-2",
    fileName: "expo-hall-b.glb",
    fileUrl: "https://picsum.photos/seed/hall2/640/360",
    kind: "glb",
    status: "processing",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-thumb-hall-2",
    fileName: "expo-hall-b-thumb.png",
    fileUrl: "https://picsum.photos/seed/hall2thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-glb-hall-3",
    fileName: "legacy-hall.glb",
    fileUrl: "https://picsum.photos/seed/hall3/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(120),
  },
  {
    id: "asset-thumb-hall-3",
    fileName: "legacy-hall-thumb.jpg",
    fileUrl: "https://picsum.photos/seed/hall3thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(120),
  },
  {
    id: "asset-glb-booth-1",
    fileName: "standard-minimal.glb",
    fileUrl: "https://picsum.photos/seed/booth1/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-thumb-booth-1",
    fileName: "standard-minimal-thumb.webp",
    fileUrl: "https://picsum.photos/seed/booth1thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-blend-booth-1",
    fileName: "standard-minimal.blend",
    fileUrl: "https://example.com/files/standard-minimal.blend",
    kind: "blend",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-glb-booth-2",
    fileName: "premium-corner.glb",
    fileUrl: "https://picsum.photos/seed/booth2/640/360",
    kind: "glb",
    status: "failed",
    createdAt: isoOffset(10),
  },
  {
    id: "asset-thumb-booth-2",
    fileName: "premium-corner-thumb.png",
    fileUrl: "https://picsum.photos/seed/booth2thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(10),
  },
  {
    id: "asset-glb-booth-3",
    fileName: "inactive-suite.glb",
    fileUrl: "https://picsum.photos/seed/booth3/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(80),
  },
  {
    id: "asset-thumb-booth-3",
    fileName: "inactive-suite-thumb.jpg",
    fileUrl: "https://picsum.photos/seed/booth3thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(80),
  },
]

export const mockHallTemplates: HallTemplate[] = [
  {
    id: "hall-template-1",
    name: "Modern Convention Hall",
    translations: [
      { languageCode: "vi", name: "Sanh Hoi Nghi Hien Dai" },
      { languageCode: "ja", name: "モダンコンベンションホール" },
    ],
    sourceBlendAssetId: "asset-blend-hall-1",
    renderGlbAssetId: "asset-glb-hall-1",
    thumbnailAssetId: "asset-thumb-hall-1",
    isPublic: true,
    isActive: true,
    updatedBy: "Khai Pham",
    updatedAt: isoOffset(6),
  },
  {
    id: "hall-template-2",
    name: "Open Expo Hall B",
    translations: [],
    renderGlbAssetId: "asset-glb-hall-2",
    thumbnailAssetId: "asset-thumb-hall-2",
    isPublic: false,
    isActive: true,
    updatedBy: "Nina Tran",
    updatedAt: isoOffset(12),
  },
  {
    id: "hall-template-3",
    name: "Legacy Industrial Hall",
    translations: [{ languageCode: "vi", name: "Sanh Cong Nghiep Co Dien" }],
    renderGlbAssetId: "asset-glb-hall-3",
    thumbnailAssetId: "asset-thumb-hall-3",
    isPublic: false,
    isActive: false,
    updatedBy: "Minh Do",
    updatedAt: isoOffset(72),
  },
]

export const mockHallTemplateSlots: HallTemplateSlot[] = [
  {
    id: "slot-1",
    hallTemplateId: "hall-template-1",
    slotCode: "A01",
    name: "Booth A01",
    posX: 2,
    posY: 0,
    posZ: 4,
    rotX: 0,
    rotY: 90,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "north", lighting: "warm" },
  },
  {
    id: "slot-2",
    hallTemplateId: "hall-template-1",
    slotCode: "A02",
    name: "Booth A02",
    posX: 6,
    posY: 0,
    posZ: 4,
    rotX: 0,
    rotY: 90,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "north" },
  },
  {
    id: "slot-3",
    hallTemplateId: "hall-template-1",
    slotCode: "B01",
    name: "Booth B01",
    posX: 2,
    posY: 0,
    posZ: 8,
    rotX: 0,
    rotY: 180,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "south" },
  },
  {
    id: "slot-4",
    hallTemplateId: "hall-template-2",
    slotCode: "C01",
    name: "Booth C01",
    posX: 0,
    posY: 0,
    posZ: 0,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 4,
    height: 2.5,
    depth: 4,
    metadata: {},
  },
]

export const mockBoothTypes: BoothType[] = [
  { id: "booth-type-basic", name: "Basic" },
  { id: "booth-type-pro", name: "Pro" },
  { id: "booth-type-premium", name: "Premium" },
]

export const mockBoothTemplates: BoothTemplate[] = [
  {
    id: "booth-template-1",
    name: "Minimal Basic Booth",
    translations: [{ languageCode: "vi", name: "Gian Hang Co Ban Toi Gian" }],
    boothTypeId: "booth-type-basic",
    sourceBlendAssetId: "asset-blend-booth-1",
    renderGlbAssetId: "asset-glb-booth-1",
    thumbnailAssetId: "asset-thumb-booth-1",
    description: "Clean and neutral setup for basic booths.",
    isPublic: true,
    isActive: true,
    updatedBy: "Khai Pham",
    updatedAt: isoOffset(8),
  },
  {
    id: "booth-template-2",
    name: "Pro Corner Neon",
    translations: [],
    boothTypeId: "booth-type-pro",
    renderGlbAssetId: "asset-glb-booth-2",
    thumbnailAssetId: "asset-thumb-booth-2",
    description: "Corner booth with dynamic light strips.",
    isPublic: false,
    isActive: true,
    updatedBy: "Nina Tran",
    updatedAt: isoOffset(4),
  },
  {
    id: "booth-template-3",
    name: "Premium Suite Executive",
    translations: [
      { languageCode: "ja", name: "プレミアムスイートエグゼクティブ" },
    ],
    boothTypeId: "booth-type-premium",
    renderGlbAssetId: "asset-glb-booth-3",
    thumbnailAssetId: "asset-thumb-booth-3",
    description: "Premium private island concept.",
    isPublic: false,
    isActive: false,
    updatedBy: "Minh Do",
    updatedAt: isoOffset(68),
  },
]

export const mockHallTemplateUsage: HallTemplateUsage[] = [
  {
    hallTemplateId: "hall-template-1",
    upcomingExpoCount: 2,
    liveExpoCount: 1,
    archivedExpoCount: 4,
  },
  {
    hallTemplateId: "hall-template-2",
    upcomingExpoCount: 0,
    liveExpoCount: 0,
    archivedExpoCount: 0,
  },
  {
    hallTemplateId: "hall-template-3",
    upcomingExpoCount: 0,
    liveExpoCount: 0,
    archivedExpoCount: 2,
  },
]

export const mockHallSlotUsage: HallSlotUsage[] = [
  { slotId: "slot-1", upcomingExpoCount: 1, liveExpoCount: 0 },
  { slotId: "slot-2", upcomingExpoCount: 0, liveExpoCount: 1 },
  { slotId: "slot-3", upcomingExpoCount: 0, liveExpoCount: 0 },
  { slotId: "slot-4", upcomingExpoCount: 0, liveExpoCount: 0 },
]

export const mockBoothTemplateUsage: BoothTemplateUsage[] = [
  {
    boothTemplateId: "booth-template-1",
    upcomingExpoBoothCount: 2,
    liveExpoBoothCount: 1,
    archivedExpoBoothCount: 6,
  },
  {
    boothTemplateId: "booth-template-2",
    upcomingExpoBoothCount: 1,
    liveExpoBoothCount: 0,
    archivedExpoBoothCount: 0,
  },
  {
    boothTemplateId: "booth-template-3",
    upcomingExpoBoothCount: 0,
    liveExpoBoothCount: 0,
    archivedExpoBoothCount: 2,
  },
]

export const mockExpoCategories: ExpoCategory[] = [
  { id: "cat-tech", name: "Technology", level: 1 },
  { id: "cat-ai", name: "Artificial Intelligence", level: 1 },
  { id: "cat-cloud", name: "Cloud & Infrastructure", level: 1 },
  { id: "cat-manufacturing", name: "Manufacturing", level: 1 },
  { id: "cat-auto", name: "Automotive", level: 1 },
  { id: "cat-food", name: "Food & Beverage", level: 1 },
  { id: "cat-organic", name: "Organic & Natural", level: 1 },
  { id: "cat-health", name: "Healthcare", level: 1 },
  { id: "cat-pharma", name: "Pharmaceuticals", level: 1 },
  { id: "cat-retail", name: "Retail & Commerce", level: 1 },
  { id: "cat-fashion", name: "Fashion & Apparel", level: 1 },
  { id: "cat-energy", name: "Energy & Environment", level: 1 },
]

function isoDate(offsetDays: number) {
  const d = new Date(now)
  d.setDate(d.getDate() + offsetDays)
  return d.toISOString().split("T")[0]
}

export const mockExpos: Expo[] = [
  {
    id: "expo-001",
    name: "VietTech Innovation Summit 2025",
    thumbnailUrl: "https://picsum.photos/seed/expo001/640/360",
    ownerEmail: "nguyen.van.a@viettech.vn",
    startDate: isoDate(30),
    endDate: isoDate(33),
    status: "Pending Review",
    categoryIds: ["cat-tech", "cat-ai"],
    createdAt: isoOffset(12),
  },
  {
    id: "expo-002",
    name: "MedWorld Asia Expo",
    thumbnailUrl: "https://picsum.photos/seed/expo002/640/360",
    ownerEmail: "admin@medworld.asia",
    startDate: isoDate(60),
    endDate: isoDate(63),
    status: "Draft",
    categoryIds: ["cat-health", "cat-pharma"],
    createdAt: isoOffset(24),
  },
  {
    id: "expo-003",
    name: "Food & Farm Global Fair",
    thumbnailUrl: "https://picsum.photos/seed/expo003/640/360",
    ownerEmail: "contact@foodfarminc.com",
    startDate: isoDate(-10),
    endDate: isoDate(5),
    status: "Live",
    categoryIds: ["cat-food", "cat-organic"],
    createdAt: isoOffset(72),
  },
  {
    id: "expo-004",
    name: "AutoDrive Expo Southeast Asia",
    thumbnailUrl: "https://picsum.photos/seed/expo004/640/360",
    ownerEmail: "info@autodrivesea.com",
    startDate: isoDate(-90),
    endDate: isoDate(-85),
    status: "Ended",
    categoryIds: ["cat-manufacturing", "cat-auto"],
    createdAt: isoOffset(200),
  },
  {
    id: "expo-005",
    name: "Fashion Forward HCMC",
    thumbnailUrl: "https://picsum.photos/seed/expo005/640/360",
    ownerEmail: "press@fashionforward.vn",
    startDate: isoDate(-120),
    endDate: isoDate(-115),
    status: "Archived",
    categoryIds: ["cat-retail", "cat-fashion"],
    createdAt: isoOffset(300),
  },
  {
    id: "expo-006",
    name: "GreenEnergy Hanoi 2025",
    thumbnailUrl: "https://picsum.photos/seed/expo006/640/360",
    ownerEmail: "ceo@greenenergy.vn",
    startDate: isoDate(45),
    endDate: isoDate(47),
    status: "Pending Review",
    categoryIds: ["cat-energy"],
    createdAt: isoOffset(6),
  },
  {
    id: "expo-007",
    name: "Cloud Connect Vietnam",
    thumbnailUrl: "https://picsum.photos/seed/expo007/640/360",
    ownerEmail: "dev@cloudconnect.io",
    startDate: isoDate(15),
    endDate: isoDate(17),
    status: "Draft",
    categoryIds: ["cat-tech", "cat-cloud"],
    createdAt: isoOffset(3),
  },
  {
    id: "expo-008",
    name: "Retail Innovation Forum 2024",
    thumbnailUrl: "https://picsum.photos/seed/expo008/640/360",
    ownerEmail: "info@retailforum.org",
    startDate: isoDate(-180),
    endDate: isoDate(-177),
    status: "Canceled",
    categoryIds: ["cat-retail"],
    createdAt: isoOffset(400),
  },
  {
    id: "expo-009",
    name: "AI & Robotics Showcase",
    thumbnailUrl: "https://picsum.photos/seed/expo009/640/360",
    ownerEmail: "showcase@airobotics.tech",
    startDate: isoDate(-5),
    endDate: isoDate(2),
    status: "Live",
    categoryIds: ["cat-tech", "cat-ai"],
    createdAt: isoOffset(48),
  },
  {
    id: "expo-010",
    name: "Pharma & Biotech Asia 2025",
    thumbnailUrl: "https://picsum.photos/seed/expo010/640/360",
    ownerEmail: "hello@pharmabiotech.com",
    startDate: isoDate(90),
    endDate: isoDate(93),
    status: "Draft",
    categoryIds: ["cat-health", "cat-pharma"],
    createdAt: isoOffset(1),
  },
  {
    id: "expo-011",
    name: "Smart Manufacturing Expo",
    thumbnailUrl: "https://picsum.photos/seed/expo011/640/360",
    ownerEmail: "ops@smartmfg.vn",
    startDate: isoDate(-60),
    endDate: isoDate(-57),
    status: "Ended",
    categoryIds: ["cat-manufacturing"],
    createdAt: isoOffset(150),
  },
  {
    id: "expo-012",
    name: "Organic Living Festival",
    thumbnailUrl: "https://picsum.photos/seed/expo012/640/360",
    ownerEmail: "team@organicliving.vn",
    startDate: isoDate(20),
    endDate: isoDate(22),
    status: "Pending Review",
    categoryIds: ["cat-food", "cat-organic"],
    createdAt: isoOffset(2),
  },
  {
    id: "expo-013",
    name: "Digital Health Summit",
    thumbnailUrl: "https://picsum.photos/seed/expo013/640/360",
    ownerEmail: "summit@digitalhealth.io",
    startDate: isoDate(-200),
    endDate: isoDate(-197),
    status: "Archived",
    categoryIds: ["cat-health", "cat-tech"],
    createdAt: isoOffset(500),
  },
  {
    id: "expo-014",
    name: "EV & Future Mobility Show",
    thumbnailUrl: "https://picsum.photos/seed/expo014/640/360",
    ownerEmail: "mobility@evshow.com",
    startDate: isoDate(75),
    endDate: isoDate(78),
    status: "Draft",
    categoryIds: ["cat-manufacturing", "cat-auto", "cat-energy"],
    createdAt: isoOffset(4),
  },
  {
    id: "expo-015",
    name: "B2B Marketplace Summit APAC",
    thumbnailUrl: "https://picsum.photos/seed/expo015/640/360",
    ownerEmail: "admin@b2bsummit.apac",
    startDate: isoDate(-3),
    endDate: isoDate(4),
    status: "Live",
    categoryIds: ["cat-retail", "cat-tech"],
    createdAt: isoOffset(96),
  },
]

// ─── Seller Mock Data ────────────────────────────────────────────────────────

/** Which booth templates the admin has made available for each expo. */
export const mockExpoBoothTemplateAssignments: ExpoBoothTemplateAssignment[] = [
  {
    expoId: "expo-001",
    boothTemplateIds: ["booth-template-1", "booth-template-3"],
  },
  {
    expoId: "expo-003",
    boothTemplateIds: ["booth-template-1", "booth-template-2"],
  },
  {
    expoId: "expo-004",
    boothTemplateIds: ["booth-template-1", "booth-template-2"],
  },
  {
    expoId: "expo-009",
    boothTemplateIds: [
      "booth-template-1",
      "booth-template-2",
      "booth-template-3",
    ],
  },
  { expoId: "expo-011", boothTemplateIds: ["booth-template-2"] },
]

/** Template-driven customization config per booth template. */
export const mockBoothTemplateCustomizationConfigs: BoothTemplateCustomizationConfig[] =
  [
    {
      boothTemplateId: "booth-template-1",
      colorSlots: 2,
      imageSlots: 1,
      productLimit: 3,
      hasVideo: false,
    },
    {
      boothTemplateId: "booth-template-2",
      colorSlots: 3,
      imageSlots: 2,
      productLimit: 5,
      hasVideo: true,
    },
    {
      boothTemplateId: "booth-template-3",
      colorSlots: 3,
      imageSlots: 4,
      productLimit: 5,
      hasVideo: true,
    },
  ]

/** Exhibitor's own B2B Marketplace product catalog. */
export const mockExhibitorCatalogProducts: ExhibitorCatalogProduct[] = [
  {
    id: "cat-prod-1",
    name: "FarmSense Pro",
    description:
      "Real-time soil and weather monitoring system with AI-driven recommendations.",
    imageUrl: "https://picsum.photos/seed/farmsense/400/300",
  },
  {
    id: "cat-prod-2",
    name: "TraceChain Platform",
    description:
      "Blockchain-backed traceability for produce from farm to shelf.",
    imageUrl: "https://picsum.photos/seed/tracechain/400/300",
  },
  {
    id: "cat-prod-3",
    name: "AgroAI Enterprise",
    description:
      "Machine learning pipeline for yield prediction and logistics optimisation.",
    imageUrl: "https://picsum.photos/seed/agroai/400/300",
  },
  {
    id: "cat-prod-4",
    name: "FieldBot Lite",
    description:
      "Autonomous field robot for crop scouting and data collection.",
    imageUrl: "https://picsum.photos/seed/fieldbot/400/300",
  },
  {
    id: "cat-prod-5",
    name: "ColdChain Monitor",
    description: "End-to-end cold storage monitoring with real-time alerts.",
    imageUrl: "https://picsum.photos/seed/coldchain/400/300",
  },
  {
    id: "cat-prod-6",
    name: "HarvestIQ",
    description:
      "Predictive analytics platform for harvest planning and yield optimisation.",
    imageUrl: "https://picsum.photos/seed/harvestiq/400/300",
  },
]

export const mockSellerRegistrations: SellerBoothRegistration[] = [
  {
    id: "reg-001",
    expoId: "expo-003",
    slotId: "slot-1",
    boothTemplateId: "booth-template-1",
    boothRef: "A01",
    boothTier: "Basic",
    status: "Live",
    purchasedAt: isoOffset(80),
  },
  {
    id: "reg-002",
    expoId: "expo-003",
    slotId: "slot-2",
    boothTemplateId: "booth-template-2",
    boothRef: "A02",
    boothTier: "Pro",
    status: "Live",
    purchasedAt: isoOffset(78),
  },
  {
    id: "reg-003",
    expoId: "expo-009",
    slotId: "slot-3",
    boothTemplateId: "booth-template-1",
    boothRef: "B01",
    boothTier: "Basic",
    status: "Configured",
    purchasedAt: isoOffset(50),
  },
  {
    // No template selected yet — demonstrates US-01 (Select Booth Template)
    id: "reg-004",
    expoId: "expo-001",
    boothRef: "C05",
    boothTier: "Premium",
    status: "Pending Setup",
    purchasedAt: isoOffset(10),
  },
  {
    id: "reg-005",
    expoId: "expo-004",
    slotId: "slot-4",
    boothTemplateId: "booth-template-1",
    boothRef: "C01",
    boothTier: "Basic",
    status: "Ended",
    purchasedAt: isoOffset(250),
  },
  {
    id: "reg-006",
    expoId: "expo-011",
    boothTemplateId: "booth-template-2",
    boothRef: "D03",
    boothTier: "Pro",
    status: "Ended",
    purchasedAt: isoOffset(180),
  },
]

export const mockBoothCustomizations: BoothCustomization[] = [
  {
    registrationId: "reg-001",
    selectedBoothTemplateId: "booth-template-1",
    publishStatus: "Published",
    colors: ["#2563eb", "#f59e0b"],
    logoUrl: "https://picsum.photos/seed/arotechlogo/200/200",
    imageUrls: ["https://picsum.photos/seed/arotechbooth1/800/500"],
    videoType: null,
    videoUrl: "",
    products: [
      {
        id: "cat-prod-1",
        name: "FarmSense Pro",
        description:
          "Real-time soil and weather monitoring system with AI-driven recommendations.",
        imageUrl: "https://picsum.photos/seed/farmsense/400/300",
      },
      {
        id: "cat-prod-2",
        name: "TraceChain Platform",
        description:
          "Blockchain-backed traceability for produce from farm to shelf.",
        imageUrl: "https://picsum.photos/seed/tracechain/400/300",
      },
    ],
  },
  {
    registrationId: "reg-002",
    selectedBoothTemplateId: "booth-template-2",
    publishStatus: "Draft",
    colors: ["#7c3aed", "#ec4899", "#14b8a6"],
    logoUrl: "https://picsum.photos/seed/arotechlogo/200/200",
    imageUrls: [
      "https://picsum.photos/seed/arotechbooth2a/800/500",
      "https://picsum.photos/seed/arotechbooth2b/800/500",
    ],
    videoType: "youtube",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    products: [
      {
        id: "cat-prod-3",
        name: "AgroAI Enterprise",
        description:
          "Machine learning pipeline for yield prediction and logistics optimisation.",
        imageUrl: "https://picsum.photos/seed/agroai/400/300",
      },
    ],
  },
  {
    registrationId: "reg-003",
    selectedBoothTemplateId: "booth-template-1",
    publishStatus: "Draft",
    colors: ["#16a34a", "#f97316"],
    logoUrl: "",
    imageUrls: [],
    videoType: null,
    videoUrl: "",
    products: [],
  },
  {
    registrationId: "reg-005",
    selectedBoothTemplateId: "booth-template-1",
    publishStatus: "Published",
    colors: ["#dc2626", "#facc15"],
    logoUrl: "https://picsum.photos/seed/arotechlogo/200/200",
    imageUrls: ["https://picsum.photos/seed/autodrivebooth/800/500"],
    videoType: null,
    videoUrl: "",
    products: [
      {
        id: "cat-prod-5",
        name: "ColdChain Monitor",
        description:
          "End-to-end cold storage monitoring with real-time alerts.",
        imageUrl: "https://picsum.photos/seed/coldchain/400/300",
      },
    ],
  },
]

// ─── Core: Streaming Service ─────────────────────────────────────────────────

export const mockStreamSessions: StreamSession[] = [
  {
    streamSessionId: "ss-001",
    status: "Active",
    hostUserId: "user-nina",
    hostDisplayName: "Nina Tran",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_abc123xyz789_session001",
    replayEnabled: true,
    replayUrl: null,
    startedAt: isoOffset(2),
    endedAt: null,
    peakViewerCount: 142,
    createdAt: isoOffset(3),
    updatedAt: isoOffset(2),
  },
  {
    streamSessionId: "ss-002",
    status: "Provisioned",
    hostUserId: "user-minh",
    hostDisplayName: "Minh Do",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_def456uvw321_session002",
    replayEnabled: false,
    replayUrl: null,
    startedAt: null,
    endedAt: null,
    peakViewerCount: null,
    createdAt: isoOffset(6),
    updatedAt: isoOffset(6),
  },
  {
    streamSessionId: "ss-003",
    status: "Provisioned",
    hostUserId: "user-khai",
    hostDisplayName: "Khai Pham",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_ghi789rst654_session003",
    replayEnabled: true,
    replayUrl: null,
    startedAt: null,
    endedAt: null,
    peakViewerCount: null,
    createdAt: isoOffset(5),
    updatedAt: isoOffset(5),
  },
  {
    streamSessionId: "ss-004",
    status: "Active",
    hostUserId: "user-khai",
    hostDisplayName: "Khai Pham",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_jkl012mno987_session004",
    replayEnabled: true,
    replayUrl: null,
    startedAt: isoOffset(0.5),
    endedAt: null,
    peakViewerCount: 89,
    createdAt: isoOffset(4),
    updatedAt: isoOffset(0.5),
  },
  {
    streamSessionId: "ss-005",
    status: "Ended",
    hostUserId: "user-nina",
    hostDisplayName: "Nina Tran",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_pqr345stu210_session005",
    replayEnabled: true,
    replayUrl: "https://replay.arobid.io/r/session005.m3u8",
    startedAt: isoOffset(96),
    endedAt: isoOffset(93),
    peakViewerCount: 317,
    createdAt: isoOffset(100),
    updatedAt: isoOffset(93),
  },
  {
    streamSessionId: "ss-006",
    status: "Ended",
    hostUserId: "user-minh",
    hostDisplayName: "Minh Do",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_vwx678yza543_session006",
    replayEnabled: false,
    replayUrl: null,
    startedAt: isoOffset(98),
    endedAt: isoOffset(95),
    peakViewerCount: 54,
    createdAt: isoOffset(100),
    updatedAt: isoOffset(95),
  },
  {
    streamSessionId: "ss-007",
    status: "Provisioned",
    hostUserId: "user-nina",
    hostDisplayName: "Nina Tran",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_bcd901efg876_session007",
    replayEnabled: true,
    replayUrl: null,
    startedAt: null,
    endedAt: null,
    peakViewerCount: null,
    createdAt: isoOffset(8),
    updatedAt: isoOffset(8),
  },
  {
    streamSessionId: "ss-008",
    status: "Provisioned",
    hostUserId: "user-nina",
    hostDisplayName: "Nina Tran",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_hij234klm109_session008",
    replayEnabled: true,
    replayUrl: null,
    startedAt: null,
    endedAt: null,
    peakViewerCount: null,
    createdAt: isoOffset(48),
    updatedAt: isoOffset(48),
  },
  {
    streamSessionId: "ss-009",
    status: "Canceled",
    hostUserId: "user-minh",
    hostDisplayName: "Minh Do",
    streamUrl: "rtmp://live.arobid.io/stream",
    streamKey: "sk_live_nop567qrs432_session009",
    replayEnabled: false,
    replayUrl: null,
    startedAt: null,
    endedAt: null,
    peakViewerCount: null,
    createdAt: isoOffset(10),
    updatedAt: isoOffset(9),
  },
]

export const mockLiveComments: LiveComment[] = [
  // Comments on ss-001 (Active - Food & Farm)
  {
    liveCommentId: "lc-001",
    streamSessionId: "ss-001",
    authorUserId: "user-khai",
    authorDisplayName: "Khai Pham",
    guestDisplayName: null,
    guestEmail: null,
    commentText: "This is incredible! The vertical farming demo is impressive.",
    isDeleted: false,
    createdAt: isoOffset(1.9),
    deletedAt: null,
    deletedByUserId: null,
  },
  {
    liveCommentId: "lc-002",
    streamSessionId: "ss-001",
    authorUserId: null,
    authorDisplayName: null,
    guestDisplayName: "Alex Chen",
    guestEmail: "alex.chen@example.com",
    commentText:
      "How much water does this system save compared to traditional methods?",
    isDeleted: false,
    createdAt: isoOffset(1.85),
    deletedAt: null,
    deletedByUserId: null,
  },
  {
    liveCommentId: "lc-003",
    streamSessionId: "ss-001",
    authorUserId: "user-minh",
    authorDisplayName: "Minh Do",
    guestDisplayName: null,
    guestEmail: null,
    commentText: "Great session! Can we get the slides after?",
    isDeleted: false,
    createdAt: isoOffset(1.8),
    deletedAt: null,
    deletedByUserId: null,
  },
  {
    liveCommentId: "lc-004",
    streamSessionId: "ss-001",
    authorUserId: null,
    authorDisplayName: null,
    guestDisplayName: "Maria Santos",
    guestEmail: "maria@agrisolutions.ph",
    commentText:
      "We have similar projects in the Philippines! Would love to connect.",
    isDeleted: false,
    createdAt: isoOffset(1.7),
    deletedAt: null,
    deletedByUserId: null,
  },
  {
    liveCommentId: "lc-005",
    streamSessionId: "ss-001",
    authorUserId: "user-khai",
    authorDisplayName: "Khai Pham",
    guestDisplayName: null,
    guestEmail: null,
    commentText: "The ROI numbers are very compelling for mid-scale farms.",
    isDeleted: false,
    createdAt: isoOffset(1.6),
    deletedAt: null,
    deletedByUserId: null,
  },
  {
    liveCommentId: "lc-006",
    streamSessionId: "ss-001",
    authorUserId: null,
    authorDisplayName: null,
    guestDisplayName: "David Nguyen",
    guestEmail: "david@farmsupply.vn",
    commentText: "What sensors do you recommend for humidity control?",
    isDeleted: false,
    createdAt: isoOffset(1.5),
    deletedAt: null,
    deletedByUserId: null,
  },
  // Comments on ss-004 (Active - B2B Marketplace)
  {
    liveCommentId: "lc-007",
    streamSessionId: "ss-004",
    authorUserId: "user-nina",
    authorDisplayName: "Nina Tran",
    guestDisplayName: null,
    guestEmail: null,
    commentText: "Excited to see the new B2B matching engine in action!",
    isDeleted: false,
    createdAt: isoOffset(0.4),
    deletedAt: null,
    deletedByUserId: null,
  },
  {
    liveCommentId: "lc-008",
    streamSessionId: "ss-004",
    authorUserId: null,
    authorDisplayName: null,
    guestDisplayName: "James Liu",
    guestEmail: "james@tradeco.sg",
    commentText: "When will the platform be available in Singapore?",
    isDeleted: false,
    createdAt: isoOffset(0.35),
    deletedAt: null,
    deletedByUserId: null,
  },
  {
    liveCommentId: "lc-009",
    streamSessionId: "ss-004",
    authorUserId: "user-minh",
    authorDisplayName: "Minh Do",
    guestDisplayName: null,
    guestEmail: null,
    commentText: "The AI-powered supplier matching is a game changer.",
    isDeleted: false,
    createdAt: isoOffset(0.3),
    deletedAt: null,
    deletedByUserId: null,
  },
]

// ─── TradeXpo: Event GoLIVE ───────────────────────────────────────────────────

export const mockGoLIVEEvents: GoLIVEEvent[] = [
  // expo-003 (Food & Farm Global Fair — Live)
  {
    goLiveEventId: "gl-001",
    expoId: "expo-003",
    streamSessionId: "ss-001",
    title: "Sustainable Farming Innovation Workshop",
    description:
      "Deep dive into vertical farming, precision agriculture, and sustainable practices reshaping the food supply chain.",
    thumbnailUrl: "https://picsum.photos/seed/golive001/640/360",
    sessionType: "Workshop",
    scheduledStartAt: isoOffset(3),
    status: "Live",
    broadcasterUserId: "user-nina",
    broadcasterDisplayName: "Nina Tran",
    createdAt: isoOffset(72),
    updatedAt: isoOffset(2),
  },
  {
    goLiveEventId: "gl-002",
    expoId: "expo-003",
    streamSessionId: "ss-002",
    title: "Future of Food Tech — Opening Keynote",
    description:
      "Industry leaders discuss global food security and the technology innovations driving the next decade.",
    thumbnailUrl: "https://picsum.photos/seed/golive002/640/360",
    sessionType: "Keynote",
    scheduledStartAt: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    status: "Scheduled",
    broadcasterUserId: "user-minh",
    broadcasterDisplayName: "Minh Do",
    createdAt: isoOffset(70),
    updatedAt: isoOffset(70),
  },
  {
    goLiveEventId: "gl-003",
    expoId: "expo-003",
    streamSessionId: "ss-003",
    title: "Live Product Demo: FarmSense Pro",
    description:
      "Watch FarmSense Pro in action — real-time soil monitoring, predictive alerts, and AI-driven recommendations.",
    thumbnailUrl: "https://picsum.photos/seed/golive003/640/360",
    sessionType: "ProductDemo",
    scheduledStartAt: null,
    status: "Ready",
    broadcasterUserId: "user-khai",
    broadcasterDisplayName: "Khai Pham",
    createdAt: isoOffset(48),
    updatedAt: isoOffset(48),
  },
  {
    goLiveEventId: "gl-008",
    expoId: "expo-003",
    streamSessionId: "ss-009",
    title: "Organic Certification Masterclass",
    description: null,
    thumbnailUrl: null,
    sessionType: "Workshop",
    scheduledStartAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    status: "Canceled",
    broadcasterUserId: "user-minh",
    broadcasterDisplayName: "Minh Do",
    createdAt: isoOffset(60),
    updatedAt: isoOffset(9),
  },
  // expo-015 (B2B Marketplace Summit APAC — Live)
  {
    goLiveEventId: "gl-004",
    expoId: "expo-015",
    streamSessionId: "ss-004",
    title: "B2B Marketplace Opening Keynote",
    description:
      "Arobid leadership presents the future of B2B trade in APAC — platform roadmap, key milestones, and live announcements.",
    thumbnailUrl: "https://picsum.photos/seed/golive004/640/360",
    sessionType: "Keynote",
    scheduledStartAt: isoOffset(1),
    status: "Live",
    broadcasterUserId: "user-khai",
    broadcasterDisplayName: "Khai Pham",
    createdAt: isoOffset(120),
    updatedAt: isoOffset(0.5),
  },
  {
    goLiveEventId: "gl-005",
    expoId: "expo-015",
    streamSessionId: "ss-007",
    title: "Supply Chain Resilience Talkshow",
    description:
      "Panel discussion on building resilient supply chains in a post-pandemic world.",
    thumbnailUrl: "https://picsum.photos/seed/golive005/640/360",
    sessionType: "Talkshow",
    scheduledStartAt: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    status: "Scheduled",
    broadcasterUserId: "user-nina",
    broadcasterDisplayName: "Nina Tran",
    createdAt: isoOffset(100),
    updatedAt: isoOffset(100),
  },
  // expo-004 (AutoDrive Expo — Ended)
  {
    goLiveEventId: "gl-006",
    expoId: "expo-004",
    streamSessionId: "ss-005",
    title: "Autonomous Vehicle Safety Panel",
    description:
      "Expert panel on regulatory frameworks and safety standards for autonomous vehicles in Southeast Asia.",
    thumbnailUrl: "https://picsum.photos/seed/golive006/640/360",
    sessionType: "Panel",
    scheduledStartAt: isoOffset(96),
    status: "Ended",
    broadcasterUserId: "user-nina",
    broadcasterDisplayName: "Nina Tran",
    createdAt: isoOffset(110),
    updatedAt: isoOffset(93),
  },
  {
    goLiveEventId: "gl-007",
    expoId: "expo-004",
    streamSessionId: "ss-006",
    title: "EV Battery Tech Workshop",
    description:
      "Hands-on workshop exploring next-generation battery technology for electric vehicles.",
    thumbnailUrl: "https://picsum.photos/seed/golive007/640/360",
    sessionType: "Workshop",
    scheduledStartAt: isoOffset(98),
    status: "Ended",
    broadcasterUserId: "user-minh",
    broadcasterDisplayName: "Minh Do",
    createdAt: isoOffset(108),
    updatedAt: isoOffset(95),
  },
  // expo-001 (VietTech Innovation Summit — Pending Review / Upcoming)
  {
    goLiveEventId: "gl-009",
    expoId: "expo-001",
    streamSessionId: "ss-008",
    title: "AI-Driven Agriculture: From Lab to Field",
    description:
      "A deep-dive workshop on applying machine learning to crop prediction and precision farming at scale.",
    thumbnailUrl: "https://picsum.photos/seed/golive009/640/360",
    sessionType: "Workshop",
    scheduledStartAt: new Date(
      Date.now() + 31 * 24 * 60 * 60 * 1000,
    ).toISOString(),
    status: "Scheduled",
    broadcasterUserId: "user-nina",
    broadcasterDisplayName: "Nina Tran",
    createdAt: isoOffset(10),
    updatedAt: isoOffset(10),
  },
]

export const mockNotifications: AdminNotification[] = [
  {
    id: "notif-001",
    kind: "approval_needed",
    title: "Expo awaiting approval",
    message:
      '"VietTech Innovation Summit 2025" submitted by nguyen.van.a@viettech.vn is pending your review.',
    relatedExpoId: "expo-001",
    createdAt: isoOffset(12),
    isRead: false,
  },
  {
    id: "notif-002",
    kind: "approval_needed",
    title: "Expo awaiting approval",
    message:
      '"GreenEnergy Hanoi 2025" submitted by ceo@greenenergy.vn is pending your review.',
    relatedExpoId: "expo-006",
    createdAt: isoOffset(6),
    isRead: false,
  },
  {
    id: "notif-003",
    kind: "approval_needed",
    title: "Expo awaiting approval",
    message:
      '"Organic Living Festival" submitted by team@organicliving.vn is pending your review.',
    relatedExpoId: "expo-012",
    createdAt: isoOffset(2),
    isRead: false,
  },
  {
    id: "notif-004",
    kind: "expo_live",
    title: "Expo is now Live",
    message:
      '"B2B Marketplace Summit APAC" went live and is now visible to the public.',
    relatedExpoId: "expo-015",
    createdAt: isoOffset(96),
    isRead: true,
  },
  {
    id: "notif-005",
    kind: "expo_live",
    title: "Expo is now Live",
    message:
      '"AI & Robotics Showcase" went live. Approval notification sent to showcase@airobotics.tech.',
    relatedExpoId: "expo-009",
    createdAt: isoOffset(48),
    isRead: true,
  },
  {
    id: "notif-006",
    kind: "expo_starting_soon",
    title: "Expo starts in 15 days",
    message:
      '"Cloud Connect Vietnam" is scheduled to start on ' +
      isoDate(15) +
      ". Ensure all resources are ready.",
    relatedExpoId: "expo-007",
    createdAt: isoOffset(3),
    isRead: false,
  },
  {
    id: "notif-007",
    kind: "expo_starting_soon",
    title: "Expo starts in 20 days",
    message: `"Organic Living Festival" is scheduled to start on ${isoDate(20)}.`,
    relatedExpoId: "expo-012",
    createdAt: isoOffset(2),
    isRead: false,
  },
  {
    id: "notif-008",
    kind: "asset_failed",
    title: "Asset processing failed",
    message:
      'GLB file for booth template "Pro Corner Neon" failed to process. Please re-upload the asset.',
    createdAt: isoOffset(10),
    isRead: false,
  },
  {
    id: "notif-009",
    kind: "expo_ended",
    title: "Expo has ended",
    message:
      '"Smart Manufacturing Expo" ended on ' +
      isoDate(-57) +
      ". Archive or review the record.",
    relatedExpoId: "expo-011",
    createdAt: isoOffset(150),
    isRead: true,
  },
  {
    id: "notif-010",
    kind: "expo_canceled",
    title: "Expo canceled",
    message:
      '"Retail Innovation Forum 2024" was canceled by the owner. No further action required.',
    relatedExpoId: "expo-008",
    createdAt: isoOffset(400),
    isRead: true,
  },
  {
    id: "notif-011",
    kind: "expo_ended",
    title: "Expo has ended",
    message:
      '"AutoDrive Expo Southeast Asia" ended on ' +
      isoDate(-85) +
      ". Consider archiving.",
    relatedExpoId: "expo-004",
    createdAt: isoOffset(200),
    isRead: true,
  },
]
