import type {
  BoothTemplate,
  BoothTemplateUsage,
  BoothType,
  Expo,
  ExpoCategory,
  HallSlotUsage,
  HallTemplate,
  HallTemplateSlot,
  HallTemplateUsage,
  ModelAsset,
} from "@/lib/tradexpo/types"

const now = new Date()

function isoOffset(hours: number) {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString()
}

export const mockAssets: ModelAsset[] = [
  {
    id: "asset-glb-hall-1",
    fileName: "modern-hall.glb",
    fileUrl: "https://picsum.photos/seed/hall1/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-thumb-hall-1",
    fileName: "modern-hall-thumb.webp",
    fileUrl: "https://picsum.photos/seed/hall1thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-blend-hall-1",
    fileName: "modern-hall.blend",
    fileUrl: "https://example.com/files/modern-hall.blend",
    kind: "blend",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-glb-hall-2",
    fileName: "expo-hall-b.glb",
    fileUrl: "https://picsum.photos/seed/hall2/640/360",
    kind: "glb",
    status: "processing",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-thumb-hall-2",
    fileName: "expo-hall-b-thumb.png",
    fileUrl: "https://picsum.photos/seed/hall2thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-glb-hall-3",
    fileName: "legacy-hall.glb",
    fileUrl: "https://picsum.photos/seed/hall3/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(120),
  },
  {
    id: "asset-thumb-hall-3",
    fileName: "legacy-hall-thumb.jpg",
    fileUrl: "https://picsum.photos/seed/hall3thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(120),
  },
  {
    id: "asset-glb-booth-1",
    fileName: "standard-minimal.glb",
    fileUrl: "https://picsum.photos/seed/booth1/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-thumb-booth-1",
    fileName: "standard-minimal-thumb.webp",
    fileUrl: "https://picsum.photos/seed/booth1thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-blend-booth-1",
    fileName: "standard-minimal.blend",
    fileUrl: "https://example.com/files/standard-minimal.blend",
    kind: "blend",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-glb-booth-2",
    fileName: "premium-corner.glb",
    fileUrl: "https://picsum.photos/seed/booth2/640/360",
    kind: "glb",
    status: "failed",
    createdAt: isoOffset(10),
  },
  {
    id: "asset-thumb-booth-2",
    fileName: "premium-corner-thumb.png",
    fileUrl: "https://picsum.photos/seed/booth2thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(10),
  },
  {
    id: "asset-glb-booth-3",
    fileName: "inactive-suite.glb",
    fileUrl: "https://picsum.photos/seed/booth3/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(80),
  },
  {
    id: "asset-thumb-booth-3",
    fileName: "inactive-suite-thumb.jpg",
    fileUrl: "https://picsum.photos/seed/booth3thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(80),
  },
]

export const mockHallTemplates: HallTemplate[] = [
  {
    id: "hall-template-1",
    name: "Modern Convention Hall",
    translations: [
      { languageCode: "vi", name: "Sanh Hoi Nghi Hien Dai" },
      { languageCode: "ja", name: "モダンコンベンションホール" },
    ],
    sourceBlendAssetId: "asset-blend-hall-1",
    renderGlbAssetId: "asset-glb-hall-1",
    thumbnailAssetId: "asset-thumb-hall-1",
    isPublic: true,
    isActive: true,
    updatedBy: "Khai Pham",
    updatedAt: isoOffset(6),
  },
  {
    id: "hall-template-2",
    name: "Open Expo Hall B",
    translations: [],
    renderGlbAssetId: "asset-glb-hall-2",
    thumbnailAssetId: "asset-thumb-hall-2",
    isPublic: false,
    isActive: true,
    updatedBy: "Nina Tran",
    updatedAt: isoOffset(12),
  },
  {
    id: "hall-template-3",
    name: "Legacy Industrial Hall",
    translations: [{ languageCode: "vi", name: "Sanh Cong Nghiep Co Dien" }],
    renderGlbAssetId: "asset-glb-hall-3",
    thumbnailAssetId: "asset-thumb-hall-3",
    isPublic: false,
    isActive: false,
    updatedBy: "Minh Do",
    updatedAt: isoOffset(72),
  },
]

export const mockHallTemplateSlots: HallTemplateSlot[] = [
  {
    id: "slot-1",
    hallTemplateId: "hall-template-1",
    slotCode: "A01",
    name: "Booth A01",
    posX: 2,
    posY: 0,
    posZ: 4,
    rotX: 0,
    rotY: 90,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "north", lighting: "warm" },
  },
  {
    id: "slot-2",
    hallTemplateId: "hall-template-1",
    slotCode: "A02",
    name: "Booth A02",
    posX: 6,
    posY: 0,
    posZ: 4,
    rotX: 0,
    rotY: 90,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "north" },
  },
  {
    id: "slot-3",
    hallTemplateId: "hall-template-1",
    slotCode: "B01",
    name: "Booth B01",
    posX: 2,
    posY: 0,
    posZ: 8,
    rotX: 0,
    rotY: 180,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "south" },
  },
  {
    id: "slot-4",
    hallTemplateId: "hall-template-2",
    slotCode: "C01",
    name: "Booth C01",
    posX: 0,
    posY: 0,
    posZ: 0,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 4,
    height: 2.5,
    depth: 4,
    metadata: {},
  },
]

export const mockBoothTypes: BoothType[] = [
  { id: "booth-type-basic", name: "Basic" },
  { id: "booth-type-pro", name: "Pro" },
  { id: "booth-type-premium", name: "Premium" },
]

export const mockBoothTemplates: BoothTemplate[] = [
  {
    id: "booth-template-1",
    name: "Minimal Basic Booth",
    translations: [{ languageCode: "vi", name: "Gian Hang Co Ban Toi Gian" }],
    boothTypeId: "booth-type-basic",
    sourceBlendAssetId: "asset-blend-booth-1",
    renderGlbAssetId: "asset-glb-booth-1",
    thumbnailAssetId: "asset-thumb-booth-1",
    description: "Clean and neutral setup for basic booths.",
    isPublic: true,
    isActive: true,
    updatedBy: "Khai Pham",
    updatedAt: isoOffset(8),
  },
  {
    id: "booth-template-2",
    name: "Pro Corner Neon",
    translations: [],
    boothTypeId: "booth-type-pro",
    renderGlbAssetId: "asset-glb-booth-2",
    thumbnailAssetId: "asset-thumb-booth-2",
    description: "Corner booth with dynamic light strips.",
    isPublic: false,
    isActive: true,
    updatedBy: "Nina Tran",
    updatedAt: isoOffset(4),
  },
  {
    id: "booth-template-3",
    name: "Premium Suite Executive",
    translations: [
      { languageCode: "ja", name: "プレミアムスイートエグゼクティブ" },
    ],
    boothTypeId: "booth-type-premium",
    renderGlbAssetId: "asset-glb-booth-3",
    thumbnailAssetId: "asset-thumb-booth-3",
    description: "Premium private island concept.",
    isPublic: false,
    isActive: false,
    updatedBy: "Minh Do",
    updatedAt: isoOffset(68),
  },
]

export const mockHallTemplateUsage: HallTemplateUsage[] = [
  {
    hallTemplateId: "hall-template-1",
    upcomingExpoCount: 2,
    liveExpoCount: 1,
    archivedExpoCount: 4,
  },
  {
    hallTemplateId: "hall-template-2",
    upcomingExpoCount: 0,
    liveExpoCount: 0,
    archivedExpoCount: 0,
  },
  {
    hallTemplateId: "hall-template-3",
    upcomingExpoCount: 0,
    liveExpoCount: 0,
    archivedExpoCount: 2,
  },
]

export const mockHallSlotUsage: HallSlotUsage[] = [
  { slotId: "slot-1", upcomingExpoCount: 1, liveExpoCount: 0 },
  { slotId: "slot-2", upcomingExpoCount: 0, liveExpoCount: 1 },
  { slotId: "slot-3", upcomingExpoCount: 0, liveExpoCount: 0 },
  { slotId: "slot-4", upcomingExpoCount: 0, liveExpoCount: 0 },
]

export const mockBoothTemplateUsage: BoothTemplateUsage[] = [
  {
    boothTemplateId: "booth-template-1",
    upcomingExpoBoothCount: 2,
    liveExpoBoothCount: 1,
    archivedExpoBoothCount: 6,
  },
  {
    boothTemplateId: "booth-template-2",
    upcomingExpoBoothCount: 1,
    liveExpoBoothCount: 0,
    archivedExpoBoothCount: 0,
  },
  {
    boothTemplateId: "booth-template-3",
    upcomingExpoBoothCount: 0,
    liveExpoBoothCount: 0,
    archivedExpoBoothCount: 2,
  },
]

export const mockExpoCategories: ExpoCategory[] = [
  { id: "cat-tech", name: "Technology", level: 1 },
  {
    id: "cat-ai",
    name: "Artificial Intelligence",
    level: 2,
    parentId: "cat-tech",
  },
  {
    id: "cat-cloud",
    name: "Cloud & Infrastructure",
    level: 2,
    parentId: "cat-tech",
  },
  { id: "cat-manufacturing", name: "Manufacturing", level: 1 },
  {
    id: "cat-auto",
    name: "Automotive",
    level: 2,
    parentId: "cat-manufacturing",
  },
  { id: "cat-food", name: "Food & Beverage", level: 1 },
  {
    id: "cat-organic",
    name: "Organic & Natural",
    level: 2,
    parentId: "cat-food",
  },
  { id: "cat-health", name: "Healthcare", level: 1 },
  {
    id: "cat-pharma",
    name: "Pharmaceuticals",
    level: 2,
    parentId: "cat-health",
  },
  { id: "cat-retail", name: "Retail & Commerce", level: 1 },
  {
    id: "cat-fashion",
    name: "Fashion & Apparel",
    level: 2,
    parentId: "cat-retail",
  },
  { id: "cat-energy", name: "Energy & Environment", level: 1 },
]

function isoDate(offsetDays: number) {
  const d = new Date(now)
  d.setDate(d.getDate() + offsetDays)
  return d.toISOString().split("T")[0]
}

export const mockExpos: Expo[] = [
  {
    id: "expo-001",
    name: "VietTech Innovation Summit 2025",
    thumbnailUrl: "https://picsum.photos/seed/expo001/640/360",
    ownerEmail: "nguyen.van.a@viettech.vn",
    startDate: isoDate(30),
    endDate: isoDate(33),
    status: "Pending Review",
    categoryIds: ["cat-tech", "cat-ai"],
    createdAt: isoOffset(12),
  },
  {
    id: "expo-002",
    name: "MedWorld Asia Expo",
    thumbnailUrl: "https://picsum.photos/seed/expo002/640/360",
    ownerEmail: "admin@medworld.asia",
    startDate: isoDate(60),
    endDate: isoDate(63),
    status: "Draft",
    categoryIds: ["cat-health", "cat-pharma"],
    createdAt: isoOffset(24),
  },
  {
    id: "expo-003",
    name: "Food & Farm Global Fair",
    thumbnailUrl: "https://picsum.photos/seed/expo003/640/360",
    ownerEmail: "contact@foodfarminc.com",
    startDate: isoDate(-10),
    endDate: isoDate(5),
    status: "Live",
    categoryIds: ["cat-food", "cat-organic"],
    createdAt: isoOffset(72),
  },
  {
    id: "expo-004",
    name: "AutoDrive Expo Southeast Asia",
    thumbnailUrl: "https://picsum.photos/seed/expo004/640/360",
    ownerEmail: "info@autodrivesea.com",
    startDate: isoDate(-90),
    endDate: isoDate(-85),
    status: "Ended",
    categoryIds: ["cat-manufacturing", "cat-auto"],
    createdAt: isoOffset(200),
  },
  {
    id: "expo-005",
    name: "Fashion Forward HCMC",
    thumbnailUrl: "https://picsum.photos/seed/expo005/640/360",
    ownerEmail: "press@fashionforward.vn",
    startDate: isoDate(-120),
    endDate: isoDate(-115),
    status: "Archived",
    categoryIds: ["cat-retail", "cat-fashion"],
    createdAt: isoOffset(300),
  },
  {
    id: "expo-006",
    name: "GreenEnergy Hanoi 2025",
    thumbnailUrl: "https://picsum.photos/seed/expo006/640/360",
    ownerEmail: "ceo@greenenergy.vn",
    startDate: isoDate(45),
    endDate: isoDate(47),
    status: "Pending Review",
    categoryIds: ["cat-energy"],
    createdAt: isoOffset(6),
  },
  {
    id: "expo-007",
    name: "Cloud Connect Vietnam",
    thumbnailUrl: "https://picsum.photos/seed/expo007/640/360",
    ownerEmail: "dev@cloudconnect.io",
    startDate: isoDate(15),
    endDate: isoDate(17),
    status: "Draft",
    categoryIds: ["cat-tech", "cat-cloud"],
    createdAt: isoOffset(3),
  },
  {
    id: "expo-008",
    name: "Retail Innovation Forum 2024",
    thumbnailUrl: "https://picsum.photos/seed/expo008/640/360",
    ownerEmail: "info@retailforum.org",
    startDate: isoDate(-180),
    endDate: isoDate(-177),
    status: "Canceled",
    categoryIds: ["cat-retail"],
    createdAt: isoOffset(400),
  },
  {
    id: "expo-009",
    name: "AI & Robotics Showcase",
    thumbnailUrl: "https://picsum.photos/seed/expo009/640/360",
    ownerEmail: "showcase@airobotics.tech",
    startDate: isoDate(-5),
    endDate: isoDate(2),
    status: "Live",
    categoryIds: ["cat-tech", "cat-ai"],
    createdAt: isoOffset(48),
  },
  {
    id: "expo-010",
    name: "Pharma & Biotech Asia 2025",
    thumbnailUrl: "https://picsum.photos/seed/expo010/640/360",
    ownerEmail: "hello@pharmabiotech.com",
    startDate: isoDate(90),
    endDate: isoDate(93),
    status: "Draft",
    categoryIds: ["cat-health", "cat-pharma"],
    createdAt: isoOffset(1),
  },
  {
    id: "expo-011",
    name: "Smart Manufacturing Expo",
    thumbnailUrl: "https://picsum.photos/seed/expo011/640/360",
    ownerEmail: "ops@smartmfg.vn",
    startDate: isoDate(-60),
    endDate: isoDate(-57),
    status: "Ended",
    categoryIds: ["cat-manufacturing"],
    createdAt: isoOffset(150),
  },
  {
    id: "expo-012",
    name: "Organic Living Festival",
    thumbnailUrl: "https://picsum.photos/seed/expo012/640/360",
    ownerEmail: "team@organicliving.vn",
    startDate: isoDate(20),
    endDate: isoDate(22),
    status: "Pending Review",
    categoryIds: ["cat-food", "cat-organic"],
    createdAt: isoOffset(2),
  },
  {
    id: "expo-013",
    name: "Digital Health Summit",
    thumbnailUrl: "https://picsum.photos/seed/expo013/640/360",
    ownerEmail: "summit@digitalhealth.io",
    startDate: isoDate(-200),
    endDate: isoDate(-197),
    status: "Archived",
    categoryIds: ["cat-health", "cat-tech"],
    createdAt: isoOffset(500),
  },
  {
    id: "expo-014",
    name: "EV & Future Mobility Show",
    thumbnailUrl: "https://picsum.photos/seed/expo014/640/360",
    ownerEmail: "mobility@evshow.com",
    startDate: isoDate(75),
    endDate: isoDate(78),
    status: "Draft",
    categoryIds: ["cat-manufacturing", "cat-auto", "cat-energy"],
    createdAt: isoOffset(4),
  },
  {
    id: "expo-015",
    name: "B2B Marketplace Summit APAC",
    thumbnailUrl: "https://picsum.photos/seed/expo015/640/360",
    ownerEmail: "admin@b2bsummit.apac",
    startDate: isoDate(-3),
    endDate: isoDate(4),
    status: "Live",
    categoryIds: ["cat-retail", "cat-tech"],
    createdAt: isoOffset(96),
  },
]
