import type {
  BoothTemplate,
  BoothTemplateUsage,
  BoothType,
  HallSlotUsage,
  HallTemplate,
  HallTemplateSlot,
  HallTemplateUsage,
  ModelAsset,
} from "@/lib/tradexpo/types"

const now = new Date()

function isoOffset(hours: number) {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString()
}

export const mockAssets: ModelAsset[] = [
  {
    id: "asset-glb-hall-1",
    fileName: "modern-hall.glb",
    fileUrl: "https://picsum.photos/seed/hall1/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-thumb-hall-1",
    fileName: "modern-hall-thumb.webp",
    fileUrl: "https://picsum.photos/seed/hall1thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-blend-hall-1",
    fileName: "modern-hall.blend",
    fileUrl: "https://example.com/files/modern-hall.blend",
    kind: "blend",
    status: "ready",
    createdAt: isoOffset(48),
  },
  {
    id: "asset-glb-hall-2",
    fileName: "expo-hall-b.glb",
    fileUrl: "https://picsum.photos/seed/hall2/640/360",
    kind: "glb",
    status: "processing",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-thumb-hall-2",
    fileName: "expo-hall-b-thumb.png",
    fileUrl: "https://picsum.photos/seed/hall2thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-glb-hall-3",
    fileName: "legacy-hall.glb",
    fileUrl: "https://picsum.photos/seed/hall3/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(120),
  },
  {
    id: "asset-thumb-hall-3",
    fileName: "legacy-hall-thumb.jpg",
    fileUrl: "https://picsum.photos/seed/hall3thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(120),
  },
  {
    id: "asset-glb-booth-1",
    fileName: "standard-minimal.glb",
    fileUrl: "https://picsum.photos/seed/booth1/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-thumb-booth-1",
    fileName: "standard-minimal-thumb.webp",
    fileUrl: "https://picsum.photos/seed/booth1thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-blend-booth-1",
    fileName: "standard-minimal.blend",
    fileUrl: "https://example.com/files/standard-minimal.blend",
    kind: "blend",
    status: "ready",
    createdAt: isoOffset(24),
  },
  {
    id: "asset-glb-booth-2",
    fileName: "premium-corner.glb",
    fileUrl: "https://picsum.photos/seed/booth2/640/360",
    kind: "glb",
    status: "failed",
    createdAt: isoOffset(10),
  },
  {
    id: "asset-thumb-booth-2",
    fileName: "premium-corner-thumb.png",
    fileUrl: "https://picsum.photos/seed/booth2thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(10),
  },
  {
    id: "asset-glb-booth-3",
    fileName: "inactive-suite.glb",
    fileUrl: "https://picsum.photos/seed/booth3/640/360",
    kind: "glb",
    status: "ready",
    createdAt: isoOffset(80),
  },
  {
    id: "asset-thumb-booth-3",
    fileName: "inactive-suite-thumb.jpg",
    fileUrl: "https://picsum.photos/seed/booth3thumb/640/360",
    kind: "thumbnail",
    status: "ready",
    createdAt: isoOffset(80),
  },
]

export const mockHallTemplates: HallTemplate[] = [
  {
    id: "hall-template-1",
    name: "Modern Convention Hall",
    translations: [
      { languageCode: "vi", name: "Sanh Hoi Nghi Hien Dai" },
      { languageCode: "ja", name: "モダンコンベンションホール" },
    ],
    sourceBlendAssetId: "asset-blend-hall-1",
    renderGlbAssetId: "asset-glb-hall-1",
    thumbnailAssetId: "asset-thumb-hall-1",
    isPublic: true,
    isActive: true,
    updatedBy: "Khai Pham",
    updatedAt: isoOffset(6),
  },
  {
    id: "hall-template-2",
    name: "Open Expo Hall B",
    translations: [],
    renderGlbAssetId: "asset-glb-hall-2",
    thumbnailAssetId: "asset-thumb-hall-2",
    isPublic: false,
    isActive: true,
    updatedBy: "Nina Tran",
    updatedAt: isoOffset(12),
  },
  {
    id: "hall-template-3",
    name: "Legacy Industrial Hall",
    translations: [{ languageCode: "vi", name: "Sanh Cong Nghiep Co Dien" }],
    renderGlbAssetId: "asset-glb-hall-3",
    thumbnailAssetId: "asset-thumb-hall-3",
    isPublic: false,
    isActive: false,
    updatedBy: "Minh Do",
    updatedAt: isoOffset(72),
  },
]

export const mockHallTemplateSlots: HallTemplateSlot[] = [
  {
    id: "slot-1",
    hallTemplateId: "hall-template-1",
    slotCode: "A01",
    name: "Booth A01",
    posX: 2,
    posY: 0,
    posZ: 4,
    rotX: 0,
    rotY: 90,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "north", lighting: "warm" },
  },
  {
    id: "slot-2",
    hallTemplateId: "hall-template-1",
    slotCode: "A02",
    name: "Booth A02",
    posX: 6,
    posY: 0,
    posZ: 4,
    rotX: 0,
    rotY: 90,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "north" },
  },
  {
    id: "slot-3",
    hallTemplateId: "hall-template-1",
    slotCode: "B01",
    name: "Booth B01",
    posX: 2,
    posY: 0,
    posZ: 8,
    rotX: 0,
    rotY: 180,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 3,
    height: 2.5,
    depth: 3,
    metadata: { zone: "south" },
  },
  {
    id: "slot-4",
    hallTemplateId: "hall-template-2",
    slotCode: "C01",
    name: "Booth C01",
    posX: 0,
    posY: 0,
    posZ: 0,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    width: 4,
    height: 2.5,
    depth: 4,
    metadata: {},
  },
]

export const mockBoothTypes: BoothType[] = [
  { id: "booth-type-basic", name: "Basic" },
  { id: "booth-type-pro", name: "Pro" },
  { id: "booth-type-premium", name: "Premium" },
]

export const mockBoothTemplates: BoothTemplate[] = [
  {
    id: "booth-template-1",
    name: "Minimal Basic Booth",
    translations: [{ languageCode: "vi", name: "Gian Hang Co Ban Toi Gian" }],
    boothTypeId: "booth-type-basic",
    sourceBlendAssetId: "asset-blend-booth-1",
    renderGlbAssetId: "asset-glb-booth-1",
    thumbnailAssetId: "asset-thumb-booth-1",
    description: "Clean and neutral setup for basic booths.",
    isPublic: true,
    isActive: true,
    updatedBy: "Khai Pham",
    updatedAt: isoOffset(8),
  },
  {
    id: "booth-template-2",
    name: "Pro Corner Neon",
    translations: [],
    boothTypeId: "booth-type-pro",
    renderGlbAssetId: "asset-glb-booth-2",
    thumbnailAssetId: "asset-thumb-booth-2",
    description: "Corner booth with dynamic light strips.",
    isPublic: false,
    isActive: true,
    updatedBy: "Nina Tran",
    updatedAt: isoOffset(4),
  },
  {
    id: "booth-template-3",
    name: "Premium Suite Executive",
    translations: [
      { languageCode: "ja", name: "プレミアムスイートエグゼクティブ" },
    ],
    boothTypeId: "booth-type-premium",
    renderGlbAssetId: "asset-glb-booth-3",
    thumbnailAssetId: "asset-thumb-booth-3",
    description: "Premium private island concept.",
    isPublic: false,
    isActive: false,
    updatedBy: "Minh Do",
    updatedAt: isoOffset(68),
  },
]

export const mockHallTemplateUsage: HallTemplateUsage[] = [
  {
    hallTemplateId: "hall-template-1",
    upcomingExpoCount: 2,
    liveExpoCount: 1,
    archivedExpoCount: 4,
  },
  {
    hallTemplateId: "hall-template-2",
    upcomingExpoCount: 0,
    liveExpoCount: 0,
    archivedExpoCount: 0,
  },
  {
    hallTemplateId: "hall-template-3",
    upcomingExpoCount: 0,
    liveExpoCount: 0,
    archivedExpoCount: 2,
  },
]

export const mockHallSlotUsage: HallSlotUsage[] = [
  { slotId: "slot-1", upcomingExpoCount: 1, liveExpoCount: 0 },
  { slotId: "slot-2", upcomingExpoCount: 0, liveExpoCount: 1 },
  { slotId: "slot-3", upcomingExpoCount: 0, liveExpoCount: 0 },
  { slotId: "slot-4", upcomingExpoCount: 0, liveExpoCount: 0 },
]

export const mockBoothTemplateUsage: BoothTemplateUsage[] = [
  {
    boothTemplateId: "booth-template-1",
    upcomingExpoBoothCount: 2,
    liveExpoBoothCount: 1,
    archivedExpoBoothCount: 6,
  },
  {
    boothTemplateId: "booth-template-2",
    upcomingExpoBoothCount: 1,
    liveExpoBoothCount: 0,
    archivedExpoBoothCount: 0,
  },
  {
    boothTemplateId: "booth-template-3",
    upcomingExpoBoothCount: 0,
    liveExpoBoothCount: 0,
    archivedExpoBoothCount: 2,
  },
]
